version: "2.2"
services:
  kibana:
    image: "kibana:7.13.4"
    container_name: "kibana"
    environment:
      -
    volumes:
      - ./kibana.yml:/usr/share/config/kibana.yml
    ports:
      - 5601:5601
    restart: always
